experiment_dir: "/tmp/dir"
train_config:
  dataset: cifar10
  optimizer_config:
    name: adam
    arguments:
      lr: 0.01
      weight_decay: 0.0
  batch_size: 128
  epochs: 10
  scheduler_config: null
  rand_weights_init: true
model_config:
  name: resnet18
metrics_n_batches: 400