name: Static Analysis

on:
  push:
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -e .[dev] -v
      - name: Run pylint
        run: pylint ablator

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -e .[dev] -v
      - name: Run mypy
        run: mypy ablator

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -e .[dev] -v
      - name: Lint with flake8
        run: |
          flake8 ./ablator/ --count --show-source --statistics
          flake8 ./ablator/ --count --max-complexity=10 --max-line-length=127 --statistics

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -e .[dev] -v
      - name: Check formatting with black
        run: |
          black --check --preview .